# frozen_string_literal: true

name: Rubocop

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
        bundler-cache: true

    - name: Run Rubocop
      run: bundle exec rubocop

    - name: Run Rubocop with auto-correct
      run: bundle exec rubocop --autocorrect

    - name: Check for remaining offenses
      run: |
        if bundle exec rubocop | grep -q "no offenses detected"; then
          echo "✅ All Rubocop offenses have been fixed!"
        else
          echo "❌ Rubocop offenses still exist"
          bundle exec rubocop
          exit 1
        fi
